name: Galleon Pack Template Java CI

on: 
  push:
    branches:
      - 1.0.x
  pull_request:
    branches:
      - 1.0.x
  schedule:
    - cron: '0 0 * * *'

jobs:
  # This just runs mvn install like a user would on cloning the repository
  wildfy-21:
    name: WildFly 21

    runs-on: ubuntu-latest

    # The pom is set up for WildFly 21 so we don't need to do anything special
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build and Test
        run: |
          mvn --version
          mvn -B install -Dqs.test

      - name: Zip Artifacts
        run: zip -R artifacts.zip 'server.log' 'surefire-reports/*.txt' 'surefire-reports/*.xml'

      - uses: actions/upload-artifact@v1
        with:
          # Expressions in the name don't seem to get resolved
          #name: ci-artifacts-mp-reactive-raw-{{job.container.id}}
          name: ci-artifacts-mp-reactive-raw
          path: artifacts.zip


  wildfly-20:
    # This adjusts the build to use the versions from wildfly master
    name: Against WildFly master

    runs-on: ubuntu-latest

    env:
      WILDFLY_VERSION: 20.0.0.Final
      WILDFLY_CORE_VERSION: 12.0.1.Final
    steps:
      - name: Checkout feature pack
        uses: actions/checkout@v2
        with:
          path: main

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8


      - name: Initialise WildFly versions
        # Needed to download everything from Maven to not pollute the output in the next steps
        run: |
          mvn -B help:evaluate -Dexpression=project.version -pl .
          mvn -B help:evaluate -Dexpression=version.org.wildfly.core -pl .
        working-directory: wildfly-master

      - name: Set WILDFLY_VERSION
        run: |
          TMP="$(mvn help:evaluate -Dexpression=project.version -pl . | grep -v '^\[')"
          echo "::set-env name=WILDFLY_VERSION::${TMP}"
        working-directory: wildfly-master

      - name: Set WILDFLY_CORE_VERSION
        run: |
          TMP="$(mvn help:evaluate -Dexpression=version.org.wildfly.core -pl . | grep -v '^\[')"
          echo "::set-env name=WILDFLY_CORE_VERSION::${TMP}"
        working-directory: wildfly-master

      - name: Show read versions
        run: |
          echo "Feature pack version ${FEATURE_PACK_VERSION}"
          echo "WildFly version ${WILDFLY_VERSION}"
          echo "WildFly Core version ${WILDFLY_CORE_VERSION}"

      - name: Build WildFly master
        run: mvn -B install -DskipTests
        working-directory: wildfly-master

      - name: Build and Test
        run: |
          mvn --version
          mvn -B install -Dversion.org.wildfly=${WILDFLY_VERSION} -Dversion.org.wildfly.core=${WILDFLY_CORE_VERSION} -Dqs.test
        working-directory: main


      - name: Zip Artifacts
        run: zip -R artifacts.zip 'server.log' 'surefire-reports/*.txt' 'surefire-reports/*.xml'
        working-directory: main

      - uses: actions/upload-artifact@v1
        with:
          # Expressions in the name don't seem to get resolved
          #name: ci-artifacts-mp-reactive-wf-master-{{job.container.id}}
          name: ci-artifacts-mp-reactive-wf-master
          path: main/artifacts.zip
